scripts:
  foo:
    name: "Foo"
    script_path: "Scripts/helloworld.sh"
  bar:
    name: "Bar"
    script: |
      echo Bar
    execution_position: :after_compile

targets:
  TargetNameA:
    - foo
    - "helloworld.yaml"
    - bar
    - "helloworld_explicit_script.yaml"
  TargetNameB:
    - "helloworld_short.yaml"
